version: 2.1


orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: cd tests
          name: In dir 
      - run:
          command: sys.path.append(os.path.abspath(os.path.join("..")))
          name: lol
      - run:
          command: import app
          name: app import 
      - run:
          command: import models
          name: models import 
      - run:
          command: python tests/mocked1.py
          name: Cal-glomerate

workflows:
  main:
    jobs:
      - build-and-test  